name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        git rm -r $GITHUB_WORKSPACE/*.bin || true
    - name: Run PlatformIO weather-usermod nodemcuv2
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/moonmodules/WLED/archive/refs/heads/weather-usermod.zip -O /tmp/WLEDtemp/mm.zip
        unzip -o /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -name "WLED-*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:nodemcuv2' >>platformio.ini
        echo 'build_flags = ${env:nodemcuv2.build_flags} -D WLED_ENABLE_MQTT -D WLED_DISABLE_LOXONE -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D USERMOD_DALLASTEMPERATURE -D USERMOD_DHT -D USERMOD_DHT_CELSIUS -D USERMOD_BME280' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:nodemcuv2.lib_deps}' >>platformio.ini
        echo '  OneWire@~2.3.5' >>platformio.ini
        echo '  https://github.com/alwynallan/DHT_nonblocking' >>platformio.ini
        echo '  BME280@~3.0.0' >>platformio.ini
        echo '  Wire' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build || true
    - name: Copy Files weather-usermod nodemcuv2
      run: |
        cd $GITHUB_WORKSPACE
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/build_weather-usermod_nodemcuv2.bin || true
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files weather-usermod nodemcuv2
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/build_weather-usermod_nodemcuv2.bin || true
        git add $GITHUB_WORKSPACE/last_update_date.txt || true
        git commit -m "Commit Custom Build" || true
        git push origin main || true

